# Generated by Django 4.2.20 on 2025-06-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='division',
            options={'ordering': ['rank']},
        ),
    ]
