# Generated by Django 4.2.20 on 2025-06-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='divisions',
            field=models.ManyToManyField(related_name='seasons', to='league.division'),
        ),
    ]
