# Generated by Django 4.2.20 on 2025-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_season_end_date_season_is_current_season_is_visible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
