# Generated by Django 4.2.20 on 2025-06-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_alter_season_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='season',
            options={'ordering': ['-start_date']},
        ),
    ]
