# Generated by Django 4.2.20 on 2025-06-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
