# Generated by Django 4.2.20 on 2025-06-05 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_week_details_week_start_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='week',
            options={'ordering': ['start_date']},
        ),
    ]
