# Generated by Django 4.2.20 on 2025-06-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_player_current_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='club_status',
            field=models.CharField(choices=[('confirmed', 'Confirmed'), ('pending', 'Pending'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
