# Generated by Django 4.2.20 on 2025-06-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0016_player_club_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['surname']},
        ),
        migrations.AddConstraint(
            model_name='player',
            constraint=models.UniqueConstraint(fields=('forename', 'surname', 'date_of_birth'), name='unique_forename_surname_dob'),
        ),
    ]
