# Generated by Django 4.2.20 on 2025-06-06 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_alter_venueinfo_options_alter_venueinfo_latitude_and_more'),
        ('league', '0017_alter_player_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['surname', 'forename']},
        ),
        migrations.CreateModel(
            name='SeasonPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fees', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_season_players', to='clubs.club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_seasons', to='league.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_players', to='league.season')),
            ],
        ),
    ]
