# Generated by Django 4.2.20 on 2025-06-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0018_alter_player_options_seasonplayer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seasonplayer',
            options={'ordering': ['player__surname', 'player__forename'], 'verbose_name_plural': 'Season players'},
        ),
        migrations.AddConstraint(
            model_name='seasonplayer',
            constraint=models.UniqueConstraint(fields=('player', 'season'), name='unique_player_and_season'),
        ),
    ]
