# Generated by Django 4.2.20 on 2025-06-06 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0020_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='division_teams', to='league.division'),
            preserve_default=False,
        ),
    ]
