# Generated by Django 4.2.20 on 2025-06-06 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_alter_venueinfo_options_alter_venueinfo_latitude_and_more'),
        ('league', '0021_team_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='club_teams', to='clubs.club'),
            preserve_default=False,
        ),
    ]
