# Generated by Django 4.2.20 on 2025-06-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0023_team_home_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
