# Generated by Django 4.2.20 on 2025-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0024_team_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=10),
        ),
    ]
