# Generated by Django 4.2.20 on 2025-06-06 16:46

from django.db import migrations, models
import django.utils.timezone
import league.validators


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0025_team_home_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='home_time',
            field=models.TimeField(default=django.utils.timezone.now, validators=[league.validators.validate_match_time]),
            preserve_default=False,
        ),
    ]
