# Generated by Django 4.2.20 on 2025-06-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0026_team_home_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
