# Generated by Django 4.2.20 on 2025-06-06 18:22

import datetime
from django.db import migrations, models
import league.validators


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0028_alter_team_options_alter_team_home_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='home_time',
            field=models.TimeField(default=datetime.time(19, 0), help_text='State the normal start time for a home game', validators=[league.validators.validate_match_time]),
        ),
    ]
