# Generated by Django 4.2.20 on 2025-06-06 18:25

import datetime
from django.db import migrations, models
import league.validators


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0029_alter_team_home_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='home_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default='monday', max_length=10, verbose_name='Home match day'),
        ),
        migrations.AlterField(
            model_name='team',
            name='home_time',
            field=models.TimeField(default=datetime.time(19, 0), validators=[league.validators.validate_match_time], verbose_name='Home match start time'),
        ),
    ]
