# Generated by Django 4.2.20 on 2025-06-06 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0030_alter_team_home_day_alter_team_home_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasonplayer',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_season_players', to='league.team'),
            preserve_default=False,
        ),
    ]
