# Generated by Django 4.2.20 on 2025-06-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0031_seasonplayer_team'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='seasonplayer',
            name='unique_player_and_season',
        ),
        migrations.RemoveField(
            model_name='seasonplayer',
            name='club',
        ),
        migrations.RemoveField(
            model_name='seasonplayer',
            name='season',
        ),
    ]
