# Generated by Django 4.2.20 on 2025-06-06 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0032_remove_seasonplayer_unique_player_and_season_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid_fees', models.BooleanField(default=False)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='player_teams', to='league.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_players', to='league.team')),
            ],
            options={
                'verbose_name_plural': 'Team players',
                'ordering': ['player__surname', 'player__forename'],
            },
        ),
        migrations.DeleteModel(
            name='SeasonPlayer',
        ),
    ]
