# Generated by Django 4.2.20 on 2025-06-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0033_teamplayer_delete_seasonplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='season_fixtures', to='league.season')),
            ],
        ),
    ]
