# Generated by Django 4.2.20 on 2025-06-07 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0034_fixture'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='division_fixtures', to='league.division'),
            preserve_default=False,
        ),
    ]
