# Generated by Django 4.2.20 on 2025-06-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0035_fixture_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='week',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='week_fixtures', to='league.week'),
            preserve_default=False,
        ),
    ]
