# Generated by Django 4.2.20 on 2025-06-07 13:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0036_fixture_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
