# Generated by Django 4.2.20 on 2025-06-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0038_fixture_home_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='away_team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='away_fixtures', to='league.team'),
            preserve_default=False,
        ),
    ]
