# Generated by Django 4.2.20 on 2025-06-07 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0045_alter_venueinfo_options_alter_venueinfo_latitude_and_more'),
        ('league', '0039_fixture_away_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='venue',
            field=models.ForeignKey(blank=True, help_text="Leave blank to auto-assign the home team's venue", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venue_fixtures', to='clubs.venue'),
        ),
    ]
