# Generated by Django 4.2.20 on 2025-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0040_fixture_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixture',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=10),
        ),
    ]
