# Generated by Django 4.2.20 on 2025-06-07 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0041_fixture_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fixture',
            options={'ordering': ['datetime']},
        ),
        migrations.AddConstraint(
            model_name='fixture',
            constraint=models.UniqueConstraint(fields=('season', 'home_team', 'away_team'), name='season_with_home_and_away_team_unique'),
        ),
    ]
