# Generated by Django 4.2.20 on 2025-06-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0043_fixtureresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureresult',
            name='winner',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away'), ('draw', 'Draw')], max_length=4),
        ),
    ]
