# Generated by Django 4.2.20 on 2025-06-16 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0044_alter_fixtureresult_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureresult',
            name='winner',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away'), ('draw', 'Draw')], help_text='This field is auto-assigned', max_length=4),
        ),
        migrations.CreateModel(
            name='SinglesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sets', models.PositiveSmallIntegerField()),
                ('away_sets', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], help_text='This field is auto-assigned', max_length=4)),
                ('away_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='away_singles_matches', to='league.player')),
                ('fixture_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_matches', to='league.fixtureresult')),
                ('home_player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='home_singles_matches', to='league.player')),
            ],
            options={
                'ordering': ['fixture_result', 'home_player', 'away_player'],
            },
        ),
        migrations.AddConstraint(
            model_name='singlesmatch',
            constraint=models.UniqueConstraint(fields=('fixture_result', 'home_player', 'away_player'), name='unique_fixture_home_away_players'),
        ),
    ]
