# Generated by Django 4.2.20 on 2025-06-16 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0046_alter_singlesmatch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlesmatch',
            options={'ordering': ['home_player', 'away_player'], 'verbose_name_plural': 'Singles matches'},
        ),
    ]
