# Generated by Django 4.2.20 on 2025-06-17 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0047_alter_singlesmatch_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_sets', models.PositiveSmallIntegerField()),
                ('away_sets', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], help_text='This field is auto-assigned', max_length=4)),
                ('away_players', models.ManyToManyField(related_name='away_doubles_matches', to='league.teamplayer')),
                ('fixture_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_match', to='league.fixtureresult')),
                ('home_players', models.ManyToManyField(related_name='home_doubles_matches', to='league.teamplayer')),
            ],
            options={
                'verbose_name_plural': 'Doubles matches',
                'ordering': ['fixture_result'],
            },
        ),
    ]
