# Generated by Django 4.2.20 on 2025-06-17 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0048_doublesmatch'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglesGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.PositiveSmallIntegerField()),
                ('home_points', models.PositiveSmallIntegerField()),
                ('away_points', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], help_text='This field is auto-assigned', max_length=4)),
                ('singles_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singles_games', to='league.singlesmatch')),
            ],
            options={
                'ordering': ['singles_match', 'set_num'],
            },
        ),
        migrations.AddConstraint(
            model_name='singlesgame',
            constraint=models.UniqueConstraint(fields=('singles_match', 'set_num'), name='unique_set_per_match'),
        ),
    ]
