# Generated by Django 4.2.20 on 2025-06-17 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0049_singlesgame_singlesgame_unique_set_per_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoublesGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_num', models.PositiveSmallIntegerField()),
                ('home_points', models.PositiveSmallIntegerField()),
                ('away_points', models.PositiveSmallIntegerField()),
                ('winner', models.CharField(blank=True, choices=[('home', 'Home'), ('away', 'Away')], help_text='This field is auto-assigned', max_length=4)),
            ],
            options={
                'ordering': ['doubles_match', 'set_num'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='singlesgame',
            name='unique_set_per_match',
        ),
        migrations.AddConstraint(
            model_name='singlesgame',
            constraint=models.UniqueConstraint(fields=('singles_match', 'set_num'), name='unique_set_per_singles_match'),
        ),
        migrations.AddField(
            model_name='doublesgame',
            name='doubles_match',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_game', to='league.doublesmatch'),
        ),
        migrations.AddConstraint(
            model_name='doublesgame',
            constraint=models.UniqueConstraint(fields=('doubles_match', 'set_num'), name='unique_set_per_doubles_match'),
        ),
    ]
