# Generated by Django 4.2.20 on 2025-06-17 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0050_doublesgame_remove_singlesgame_unique_set_per_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublesgame',
            name='doubles_match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubles_games', to='league.doublesmatch'),
        ),
    ]
