# Generated by Django 4.2.20 on 2025-05-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_enquiry_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
