# Generated by Django 4.2.20 on 2025-05-10 17:13

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_enquiry_submitted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
