# Generated by Django 4.2.20 on 2025-05-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_alter_enquiry_options_enquiry_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-submitted_at'], 'verbose_name_plural': 'Enquiries'},
        ),
    ]
