# Generated by Django 4.2.20 on 2025-05-09 15:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='active_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
