# Generated by Django 4.2.20 on 2025-05-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_newsitem_active_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='active_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
