# Generated by Django 4.2.20 on 2025-05-10 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsitem_active_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsitem',
            options={'ordering': ['-active_from', 'title']},
        ),
    ]
