# Generated by Django 4.2.20 on 2025-05-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_alter_club_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='club',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='info', to='clubs.club'),
            preserve_default=False,
        ),
    ]
