# Generated by Django 4.2.20 on 2025-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_clubinfo_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
