# Generated by Django 4.2.20 on 2025-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_clubinfo_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='contact_name',
            field=models.CharField(default='Bob', max_length=100),
            preserve_default=False,
        ),
    ]
