# Generated by Django 4.2.20 on 2025-05-15 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_clubinfo_contact_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='contact_email',
            field=models.EmailField(default='example@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
