# Generated by Django 4.2.20 on 2025-05-15 17:09

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_clubinfo_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
