# Generated by Django 4.2.20 on 2025-05-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_clubinfo_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubinfo',
            old_name='phone',
            new_name='contact_phone',
        ),
    ]
