# Generated by Django 4.2.20 on 2025-05-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_rename_phone_clubinfo_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(default='Great club', max_length=500),
            preserve_default=False,
        ),
    ]
