# Generated by Django 4.2.20 on 2025-05-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_clubinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
