# Generated by Django 4.2.20 on 2025-05-15 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_alter_clubinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='session_info',
            field=models.TextField(default='Session info here'),
            preserve_default=False,
        ),
    ]
