# Generated by Django 4.2.20 on 2025-05-15 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0012_clubinfo_session_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='beginners',
            field=models.BooleanField(default=False),
        ),
    ]
