# Generated by Django 4.2.20 on 2025-05-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_clubinfo_advanced'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='kids',
            field=models.BooleanField(default=False),
        ),
    ]
