# Generated by Django 4.2.20 on 2025-05-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_clubinfo_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='adults',
            field=models.BooleanField(default=False),
        ),
    ]
