# Generated by Django 4.2.20 on 2025-05-15 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_clubinfo_coaching'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='league',
            field=models.BooleanField(default=False),
        ),
    ]
