# Generated by Django 4.2.20 on 2025-05-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_clubinfo_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='equipment_provided',
            field=models.BooleanField(default=False),
        ),
    ]
