# Generated by Django 4.2.20 on 2025-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_clubinfo_equipment_provided'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubinfo',
            name='membership_required',
            field=models.BooleanField(default=False),
        ),
    ]
