# Generated by Django 4.2.20 on 2025-05-16 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_alter_clubinfo_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'ordering': ['club', '-created_on'], 'verbose_name_plural': 'Enquiries'},
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
