# Generated by Django 4.2.20 on 2025-05-16 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_alter_club_options_alter_clubinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'ordering': ['club', '-created_on'], 'verbose_name_plural': 'Club info versions'},
        ),
    ]
