# Generated by Django 4.2.20 on 2025-05-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_alter_clubinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='club',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='clubinfo',
            options={'ordering': ['club', '-created_on'], 'verbose_name_plural': 'Club Information'},
        ),
    ]
