# Generated by Django 4.2.20 on 2025-05-17 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_venue_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='address_line_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
