# Generated by Django 4.2.20 on 2025-05-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_venue_address_line_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='city',
            field=models.CharField(default='York', max_length=100),
            preserve_default=False,
        ),
    ]
