# Generated by Django 4.2.20 on 2025-05-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_venue_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='county',
            field=models.CharField(default='Yorkshire', max_length=100),
            preserve_default=False,
        ),
    ]
