# Generated by Django 4.2.20 on 2025-05-17 15:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_venue_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='num_tables',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
