# Generated by Django 4.2.20 on 2025-05-17 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_venue_num_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='parking_info',
            field=models.TextField(default='Park anywhere', max_length=500),
            preserve_default=False,
        ),
    ]
