# Generated by Django 4.2.20 on 2025-05-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0034_venue_parking_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='meets_league_standards',
            field=models.BooleanField(default=False),
        ),
    ]
