# Generated by Django 4.2.20 on 2025-05-17 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_venue_meets_league_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
