# Generated by Django 4.2.20 on 2025-05-17 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0036_venue_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='postcode',
            field=models.CharField(default='HU16 PNF', max_length=8),
            preserve_default=False,
        ),
    ]
