# Generated by Django 4.2.20 on 2025-05-17 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_venue_postcode'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Venue',
            new_name='VenueInfo',
        ),
    ]
