# Generated by Django 4.2.20 on 2025-05-17 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venueinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='venueinfo',
            name='venue',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='venue_infos', to='clubs.venue'),
            preserve_default=False,
        ),
    ]
