# Generated by Django 4.2.20 on 2025-05-17 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_remove_venueinfo_name_venueinfo_venue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubVenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_venues', to='clubs.club')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_clubs', to='clubs.venue')),
            ],
            options={
                'ordering': ['club', 'venue'],
                'unique_together': {('club', 'venue')},
            },
        ),
    ]
