# Generated by Django 4.2.20 on 2025-05-17 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_clubvenue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_infos', to='clubs.club'),
        ),
    ]
