# Generated by Django 4.2.20 on 2025-05-30 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0044_venueinfo_latitude_venueinfo_longitude'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venueinfo',
            options={'ordering': ['venue', '-created_on']},
        ),
        migrations.AlterField(
            model_name='venueinfo',
            name='latitude',
            field=models.FloatField(blank=True, help_text='This field is autopopulated from the postcode.', null=True),
        ),
        migrations.AlterField(
            model_name='venueinfo',
            name='longitude',
            field=models.FloatField(blank=True, help_text='This field is autopopulated from the postcode.', null=True),
        ),
    ]
