# Generated by Django 4.2.20 on 2025-06-12 09:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0045_alter_venueinfo_options_alter_venueinfo_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
