# Generated by Django 4.2.20 on 2025-06-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0047_clubreview_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='headline',
            field=models.CharField(default='Headline', max_length=100),
            preserve_default=False,
        ),
    ]
