# Generated by Django 4.2.20 on 2025-06-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0048_clubreview_headline'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='review_text',
            field=models.TextField(default='My review'),
            preserve_default=False,
        ),
    ]
