# Generated by Django 4.2.20 on 2025-06-12 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0049_clubreview_review_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
