# Generated by Django 4.2.20 on 2025-06-12 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0050_clubreview_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
