# Generated by Django 4.2.20 on 2025-06-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0051_clubreview_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubreview',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
