# Generated by Django 4.2.20 on 2025-06-12 10:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clubs', '0052_clubreview_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubreview',
            options={'ordering': ['-updated_on']},
        ),
        migrations.AlterUniqueTogether(
            name='clubreview',
            unique_together={('club', 'user')},
        ),
    ]
