# Generated by Django 4.2.20 on 2025-06-27 21:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0053_alter_clubreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubinfo',
            name='image',
            field=cloudinary.models.CloudinaryField(default='placeholder', help_text='Recommended format: landscape, 1200x800px, JPG or PNG.', max_length=255, verbose_name='image'),
        ),
    ]
